name: build pdf

on:
  push:
    branches: [main]
    paths:
      - "**/*.tex"
      - "Makefile"

env:
  PDF_FILE_NAME: Ahmad_Musafir_Khoirul_Fattah_FullStack_Backend_Focused.pdf

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: latexmk -pdf main.tex

      - name: Rename PDF
        run: mv main.pdf ${{ env.PDF_FILE_NAME }}

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: cv.pdf
          path: ${{ env.PDF_FILE_NAME }}

      - name: Create/Update Release
        uses: softprops/action-gh-release@v3.0.2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: latest
          files: ${{ env.PDF_FILE_NAME }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
